### ISSUE TITLE
Hope sinicization

### ISSUE THREAD

**Issue by lmuiotctf** [deepanshu88/excelChatGPT#1]
If you can provide the source code, I will sinicize it here, otherwise the Chinese side will struggle with English

**Comment by lmuiotctf** [comment]
It is also hoped that the URL of the API supports customization, otherwise some regions cannot be directly accessed

**Comment by deepanshu88** [comment]
You can find the source code here : https://www.listendata.com/2023/03/how-to-run-chatgpt-inside-excel.html

ChatGPT is banned in China and Hong Kong so I don't think API will work.

**Comment by lmuiotctf** [comment]
It is currently not accessible, so I would like to add a custom API URL

**Comment by lmuiotctf** [comment]
Currently the link you provided does not have completed the code
