### ISSUE TITLE
Batch Prompt

### ISSUE THREAD

**Issue by vozer** [deepanshu88/excelChatGPT#10]
Hey!
I am looking into the Batch_run (assistant loop) script and i am wondering how i could use this with my use case.
I use the plugin with AIAssistant_QnA(Base_AI_Assistant!$A$2;Sheet1!A1).
This Formula is in Cell B1.
Cell B2 Sheet1!A2, Cell B3, Sheet1!A3 etc.

Your Batch Code uses the normal question system only.
How could i tell it to use the formula above and iterate down?
![image](https://github.com/user-attachments/assets/8211b6cd-d26f-4170-8247-2113a956f451)

thx

**Comment by deepanshu88** [comment]
Can't you drag the formula down? If you want to automate it, you can write VBA code. Refer to the documentation to loop through multiple cells..

**Comment by vozer** [comment]
Yes i did that but in your VBA Code you are not using a formula in a cell.
The problem is, that dragging it down for thousands of rows is a little bit tedious.
And i can not "prefill" the Formula so he does not calculate it at the moment, as soon as i hit enter he executes it.
So this is also why i can not "loop" through the cell.

How would you adapt this parts to use my formula and write the output in the same field B1,2,3?

  ' Call the AIAssistant function with the cell value
            result = Application.Run("AIAssistant", cell.Value)
            
' Paste the value back into the adjacent column
            cell.Offset(0, 1).Value = result

**Comment by vozer** [comment]
Never mind, got it done with ChatGPT haha, here it is:

`Sub AIAssistantLoop_SelectCellsWithTimeout()

    Dim ws As Worksheet
    Dim promptRng As Range
    Dim refColumn As Range
    Dim cell As Range
    Dim refCell As Range
    Dim visibleCells As Range
    Dim rowCount As Long
    Dim processedRows As Long

    ' Set the active sheet as the working sheet
    Set ws = ActiveSheet

    ' Allow the user to select the range of cells for prompts
    On Error Resume Next
    Set promptRng = Application.InputBox("Select the range of cells for prompts:", "Select Prompt Range", Type:=8)
    On Error GoTo 0

    ' Check if the range selection was canceled or invalid
    If promptRng Is Nothing Then
        MsgBox "No range selected. Exiting.", vbExclamation, "Canceled"
        Exit Sub
    End If

    ' Allow the user to select the column for the reference cells
    On Error Resume Next
    Set refColumn = Application.InputBox("Select a single column for the reference cells (e.g., J:J):", "Select Reference Column", Type:=8)
    On Error GoTo 0

    ' Check if the column selection was canceled or invalid
    If refColumn Is Nothing Then
        MsgBox "No reference column selected. Exiting.", vbExclamation, "Canceled"
        Exit Sub
    End If

    ' Restrict to only visible cells within the range
    On Error Resume Next
    Set visibleCells = promptRng.SpecialCells(xlCellTypeVisible)
    On Error GoTo 0

    ' Check if there are any visible cells
    If Not visibleCells Is Nothing Then
        processedRows = 0

        ' Loop through visible cells only
        For Each cell In visibleCells
            ' Check if the cell is not empty
            If Not IsEmpty(cell.Value) Then
                ' Get the corresponding cell in the selected reference column
                Set refCell = ws.Cells(cell.Row, refColumn.Column)
                
                ' Write the formula into the prompt cell
                cell.Formula = "=AIAssistant_QnA(Base_AI_Assistant!$A$2, " & refCell.Address & ")"
                
                ' Increment processed row count
                processedRows = processedRows + 1

                ' Pause execution every 500 rows
                If processedRows Mod 500 = 0 Then
                    MsgBox "Pausing for 1 minute after processing 500 rows. Click OK to resume."
                    Application.Wait Now + TimeValue("00:01:00")
                End If
            End If
        Next cell

        MsgBox "Processing complete.", vbInformation, "Finished"

    Else
        MsgBox "No visible cells found in the selected range.", vbExclamation, "Error"
    End If

End Sub
`
