### ISSUE TITLE
can you add another option Forwarding Host/API Host/custom endpoints

### ISSUE THREAD

**Issue by Emieanderson** [deepanshu88/excelChatGPT#2]
can you add another option Forwarding Host/API Host/custom endpoints for adding my custom host for my custom api key

**Comment by deepanshu88** [comment]
It's not aligned with the objective of this repository. To implement any custom API using VBA, you can see the VBA code here - https://www.listendata.com/2023/03/how-to-run-chatgpt-inside-excel.html

**Comment by Emieanderson** [comment]
can i have the password of script
