### ISSUE TITLE
Error message 'No input found'

### ISSUE THREAD

**Issue by JasonSijssens** [deepanshu88/excelChatGPT#4]
Hello,

This tool looks great!
However, I always get an error message 'No input found' when using the tool.
What could I be doing wrong?

![image](https://github.com/deepanshu88/excelChatGPT/assets/113061785/04e2422a-06b7-4c36-a597-f25814377f36)

![image](https://github.com/deepanshu88/excelChatGPT/assets/113061785/87018bff-714e-4aa7-a0e7-cec35cf9da65)

Thanks in advance!
Jason

**Comment by deepanshu88** [comment]
Try the function =AIAssistant(A1). What does it return?

**Comment by JasonSijssens** [comment]
It gives a #VALUE! error:

![image](https://github.com/deepanshu88/excelChatGPT/assets/113061785/86d7e6aa-8513-4642-b39a-af95e7e48213)

**Comment by deepanshu88** [comment]
It seems either the API is blocked on your end, your API key has expired, or it is not a paid one. I just checked again at my end and it works fine.
