### ISSUE TITLE
How can i be sure that this plugin is safe?

### ISSUE THREAD

**Issue by vozer** [deepanshu88/excelChatGPT#8]
Hello! I would really like to use my plugin in my excel but since it has sensitive data i want to be sure that this xaml does not have any malicious code. Since it is password protected i can not make sure of this.

**Comment by deepanshu88** [comment]
Upload file on virus total and test it - https://www.virustotal.com/gui/home/upload

**Comment by vozer** [comment]
There is one begign comment and 5 of 60 Virus Detectors detect something.
https://www.virustotal.com/gui/file/bdba47a1e9cc11d98abf3d4639ab4d2e78054e87d51787c1788b9b3adbf028aa

![2024-10-22 12_43_48-VirusTotal - File - bdba47a1e9cc11d98abf3d4639ab4d2e78054e87d51787c1788b9b3adbf0](https://github.com/user-attachments/assets/f31fdb93-670e-4fb2-a496-e39804d211ea)

**Comment by deepanshu88** [comment]
Benign means not harmful. Some vendors generally flag VBA code as false positives. Everytime you run, you would find different score.
<img width="577" alt="test" src="https://github.com/user-attachments/assets/03849b7c-a998-4acf-a276-9d7526209b81">
