### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by vozer** [deepanshu88/excelChatGPT#9]
Hi, i want to use the plugin for filling up Data in Cells based on a reference. Since this reference is quite big i dont want to send it everytime to ChatGPT (costs). is there a way to allow embeddings? Imagine embedding a Sheet of Reference Data like:

text, topic, subtopic
text, topic, subtopic

and the prompt would be:
Take Text in B3 and embedding info to correctly fill C3 with the topic and D3 with the subtopic.

**Comment by deepanshu88** [comment]
No as of now.
